= Multiple Windows/Dialogs
Seabstian Hager, Valentin Weinhäuple
1.0.0, 2022-02-07: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Overview
    In unserer Presentation wird das Thema Popup Windows und Dialog Fenster behandelt.
    Wir erklären Ihnen das Grundwissen zum Thema und wie sie es im Code implementieren mit einem praktischem Beispiel. 6


== Praxis
* Neue Stage und Scene anlegen
* Content in neu angelegte Scene einfügen
* stage.show() um neues Fenster zu zeigen

== Dialogs
* Information Dialog
* Warning Dialog
* Error Dialog
* Exception Dialog
* Confirmation Dialog
* Text Input Dialog
* Choice Dialog
* Custom Login Dialog
* https://code.makery.ch/blog/javafx-dialogs-official/


== Code Example

[source, java]
----
public class HelloApplication extends Application {
    @Override
    public void start(final Stage stage) throws IOException {

        Button btn = new Button("click");
        StackPane root = new StackPane();
        root.getChildren().addAll(btn);

        btn.setOnAction(new EventHandler<ActionEvent>() {<.>
            @Override
            public void handle(ActionEvent actionEvent) {
                TextField username = new TextField();
                Button commit = new Button("commit");
                VBox secondRoot = new VBox();
                secondRoot.getChildren().addAll(username, commit);

                Stage secondStage = new Stage();

                Scene secondScene = new Scene(secondRoot, 320, 240);
                secondStage.setTitle("second-window");
                secondStage.setScene(secondScene);


                commit.setOnAction(new EventHandler<ActionEvent>() {
                    @Override
                    public void handle(ActionEvent actionEvent) {
                        System.out.println("username: " + username.getText());
                        secondStage.close();
                    }
                });

                secondStage.initOwner(stage);<.>
                secondStage.initModality(Modality.APPLICATION_MODAL);
                secondStage.showAndWait();
            }
        });

        Scene scene = new Scene(root, 320, 240);
        stage.setTitle("first-window");
        stage.setScene(scene);
        stage.show();
    }
----
<.> Onclick zum öffnen des zweiten Fensters
<.> Zum sperren von dem ersten Fenster
